---
output:
  html_document:
    highlight: haddock
    theme: cerulean
    toc: no
  pdf_document:
    toc: no
  word_document:
    toc: no
---

# Casey O'Hara

Bren School of Environmental Science & Management

casey.c.ohara@gmail.com | cohara@bren.ucsb.edu
<!-- ## Curriculum Vitae {.tabset} -->

<!-- ### Education and Experience -->

## Education

__PhD Environmental Science and Management (2022 expected)__<br>
Bren School of Environmental Science & Management, University of California, Santa Barbara<br>
_Advisor: Dr. Benjamin Halpern_
<!-- * Committee:  -->

__Master of Environmental Science and Management (2014)__<br>
Bren School of Environmental Science & Management, University of California, Santa Barbara<br>
_UCSB University Award of Distinction; Bren School Academic Achievement Award_

__Single Subject Teaching Credential in Science, Physics (2004)__<br>
Graduate School of Education, San Francisco State University

__Master of Science in Mechanical Engineering Design (1994)__<br>
Department of Mechanical Engineering, Design Division, Stanford University

__Bachelor of Science in Mechanical Engineering (1993)__<br>
Department of Mechanical Engineering, Stanford University

## Experience

__Project scientist, Ocean Health Index__ (January 2015 – present) <br>
National Center for Ecological Analysis and Synthesis - Santa Barbara, CA

__AAAS Mass Media Science Fellowship__ (June 2014 - August 2014) <br>
_The Oregonian_ - Portland, OR

__Program Consultant__ (June 2013 - August 2013) <br>
The School for Examining Essential Questions of Sustainability (SEEQS) Charter School - Honolulu, HI

__Masters Thesis Group Project__ (April 2013 - June 2014) <br>
UCSB Bren School - Santa Barbara, CA “Offshore wind energy in the context of multiple ocean uses on the Bermuda platform.” Client: Department of Environmental Protection, Bermuda

See also _STEM Education and Engineering_

## Working Groups

* __Species Vulnerability Working Group (National Philanthropic Trust)__ (February 2020) <br>
Matadradra Serua, Fiji
* __Coastal Outcomes Working Group (SNAPP)__ (April 2019) <br>
National Center for Ecological Analysis and Synthesis - Santa Barbara, CA
* __Ocean Futures Working Group (SNAPP)__ (July 2018) <br>
National Center for Ecological Analysis and Synthesis - Santa Barbara, CA


## Relevant Technical Skills

*	R/R Studio including spatial analysis, data visualization, package development, ShinyApps
* Git/GitHub
*	MATLAB, Stata, C/C++, HTML, JavaScript, LaTeX
*	ArcGIS, QGIS

## Publications

* __O'Hara, Casey C.__, Courtney Scarborough, Karen L. Hunter, Jamie C. Afflerbach, Karin Bodtker, Melanie Frazier, Julia S. Stewart Lowndes, R. Ian Perry, and Benjamin S. Halpern. 2020. “Changes in Ocean Health in British Columbia from 2001 to 2016.” PLOS ONE 15 (1): e0227502. https://doi.org/10.1371/journal.pone.0227502.
* Friedman, Whitney R., Benjamin S. Halpern, Elizabeth McLeod, Michael W. Beck, Carlos M. Duarte, Carrie V. Kappel, Arielle Levine, ... __Casey O'Hara__, et al. 2020. “Research Priorities for Achieving Healthy Marine Ecosystems and Human Communities in a Changing Climate.” Frontiers in Marine Science 7. https://doi.org/10.3389/fmars.2020.00005.
* Halpern, Benjamin S., Melanie Frazier, Jamie Afflerbach, Julia S. Lowndes, Fiorenza Micheli, __Casey O'Hara__, Courtney Scarborough, and Kimberly A. Selkoe. 2019. “Recent Pace of Change in Human Impact on the World's Ocean.” Scientific Reports 9 (1): 1–8. https://doi.org/10.1038/s41598-019-47201-9.
* __O’Hara, Casey C.__, Juan Carlos Villaseñor‐Derbez, Gina M. Ralph, and Benjamin S. Halpern. 2019. “Mapping Status and Conservation of Global At‐risk Marine Biodiversity.” Conservation Letters, May, e12651. https://doi.org/10.1111/conl.12651.
* Burgass, Michael J., E. J. Milner-Gulland, Julia S. Stewart Lowndes, __Casey O'Hara__, Jamie C. Afflerbach, and Benjamin S. Halpern. 2018. “A Pan-Arctic Assessment of the Status of Marine Social-Ecological Systems.” Regional Environmental Change, August. https://doi.org/10.1007/s10113-018-1395-6.
* Halpern, Benjamin S., Melanie Frazier, Jamie Afflerbach, __Casey O'Hara__, Steven Katona, Julia S. Stewart Lowndes, Ning Jiang, Erich Pacheco, Courtney Scarborough, and Johanna Polsenberg. 2017. “Drivers and Implications of Change in Global Ocean Health over the Past Five Years.” Edited by Athanassios C. Tsikliras. PLOS ONE 12 (7): e0178267. https://doi.org/10.1371/journal.pone.0178267.
* Lowndes, Julia S. Stewart, Benjamin D. Best, Courtney Scarborough, Jamie C. Afflerbach, Melanie R. Frazier, __Casey C. O'Hara__, Ning Jiang, and Benjamin S. Halpern. 2017. “Our Path to Better Science in Less Time Using Open Data Science Tools.” Nature Ecology & Evolution 1 (6): 0160. https://doi.org/10.1038/s41559-017-0160.
* __O'Hara, Casey C.__, Jamie C. Afflerbach, Courtney Scarborough, Kristin Kaschner, and Benjamin S. Halpern. 2017. “Aligning Marine Species Range Data to Better Serve Science and Conservation.” Edited by Robert Guralnick. PLOS ONE 12 (5): e0175739. https://doi.org/10.1371/journal.pone.0175739.

\newpage
## STEM Education and Engineering

### Science Education Experience

<!-- * (TA position) -->
<!-- * (Unit design, Lever coaching, Exploratorium workshop) -->
* Program Consultant (June 2013 - August 2013) The School for Examining Essential Questions of Sustainability (SEEQS) Charter School - Honolulu, HI
* Science Teacher: Physics, Integrated Science, Engineering & Green Tech (August 2004 - June 2012) Carlmont High School - Belmont, CA
* Education Liaison (November 2009 - December 2009) Amundsen-Scott South Pole Station, Antarctica

### Science Education Leadership and Honors

* “Where the Wonder Went” documentary short film, Santa Barbara International Film Festival (January 2014) Santa Barbara, CA
* Senior Fellow, Knowles Science Teaching Foundation (2009 - present) - Moorestown, NJ
* Teaching Fellow, Knowles Science Teaching Foundation (2004 - 2009) - Moorestown, NJ
* Exploratorium Teacher Institute (2004 - 2013) - San Francisco, CA
* Innovative Teacher of the Year (2011) Carlmont High School - Belmont, CA
* Amgen Award for Science Teaching Excellence (2011) Amgen Corporation 
* National Board Certification (Science - Adolescent/Young Adult) (2009) National Board for Professional Teaching Standards

### Engineering Experience

* Mechanical Engineer (May 2000 - December 2003) St. Jude Medical, Inc. - Sunnyvale, CA 
* Mechanical Engineer (May 1997 - May 2000) Asyst Technologies (Hine Design) - Sunnyvale, CA 
* Mechanical Engineer (August 1995 - April 1997) Applied Materials, Inc. - Santa Clara, CA 
* Maintenance Engineer (August 1994 - August 1995) ATMEL Inc. - San Jose, CA 


